# For more configuration details:
# https://docs.codecov.io/docs/codecov-yaml

# Check if this file is valid by running in bash:
# curl -X POST --data-binary @.codecov.yml https://codecov.io/validate

# Ignoring Paths
# --------------
# which folders/files to ignore
ignore:
  - SWDestinyTrades/Classes/Generated/.*
  