# .slather.yml

workspace: swdestiny-trades.xcworkspace
xcodeproj: swdestiny-trades.xcodeproj
scheme: SWDestiny-Trades
coverage_service: html
source_directory: "SWDestiny Trades/Classes"
output_directory: coverage_report
ignore:
  - ../**/*/Xcode*
  - ../core/*  
  - Pods/*
  