opt_in_rules:                                                                                                              
  - closure_end_indentation                                                                                                
  - closure_spacing                                                                                                        
  - discouraged_object_literal                                                                                             
  - empty_count                                                                                                            
  - explicit_init                                                                                                          
  - fatal_error_message                                                                                                    
  - file_header                                                                                                            
  - file_length                                                                                                            
  - first_where                                                                                                            
  - force_cast                                                                                                             
  - force_try                                                                                                              
  - force_unwrapping                                                                                                       
  - implicitly_unwrapped_optional                                                                                          
  - joined_default_parameter                                                                                               
  - multiline_parameters                                                                                                   
  - operator_usage_whitespace                                                                                              
  - overridden_super_call                                                                                                  
  - prefixed_toplevel_constant 
  - private_action                                                                                                         
  - prohibited_super_call                                                                                                  
  - redundant_nil_coalescing                                                                                               
  - trailing_closure                                                                                                       
  - unneeded_parentheses_in_closure_argument                                                                               
  - vertical_parameter_alignment_on_call                                                                                   
  - yoda_condition  

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Carthage

custom_rules:
quickspec_class_name:
  name: "Invalid Test Class Name"
  regex: "class\\s+(.*)[^Tests]:\\s+QuickSpec"
  message: "A test class name must end with 'Tests'"
  severity: error
  