import ProjectDescription

let workspace = Workspace(name: "swdestiny-trades",
                          projects: ["./**"],
                          generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled))
