# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/
references:
    defaults: &defaults
        macos:
            xcode: "12.0.0"
        shell: /bin/bash --login -eo pipefail
        working_directory: ~/swdestiny-trades
        environment:
            BUNDLE_PATH: vendor/bundle

    restore_bundle_cache: &restore_bundle_cache
        restore_cache:
            keys:
                - v1-gems-{{ checksum "Gemfile.lock" }}
                # Fall back to using the latest cache if no exact match is found.
                - v1-gems-

    save_bundle_cache: &save_bundle_cache
        save_cache:
            key: v1-gems-{{ checksum "Gemfile.lock" }}
            paths:
                - vendor/bundle

    bunde_install: &bunde_install
        run:
          name: "Install bundle"
          command: bundle check || bundle install

version: 2.1
jobs:
  tests:
    <<: *defaults
    steps:
      - checkout
      - *restore_bundle_cache
      - *bunde_install
      - *save_bundle_cache
      - run:
          name: "Create output dir"
          command: mkdir output
      - run:
          name: "Run tests in Swift 5.3"
          command: xcodebuild -workspace 'swdestiny-trades.xcworkspace' -sdk 'iphonesimulator' -scheme 'SWDestiny-Trades' -destination 'name=iPhone X' SWIFT_VERSION=5.3 build test | tee output/xcodebuild_swift5.3.log | xcpretty --color --simple
      - run:
          name: "Swiftlint"
          command: |
               HOMEBREW_NO_AUTO_UPDATE=1 brew install swiftlint
               swiftlint lint --no-cache --reporter junit | tee result.xml
      - store_artifacts:
          path: result.xml
      - store_artifacts:
          path: output/
      - store_artifacts:
          path: ~/Nimble-Snapshots/Bootstrap/BootstrapTests/FailureDiffs/
      - store_test_results:
          path: result.xml
      - store_test_results:
          path: output/

workflows:
  version: 2.1
  build-and-test:
    jobs:
      - tests
