disabled_rules: # rule identifiers to exclude from running
  - cyclomatic_complexity
  - file_length
  - force_cast
  - force_try
  - force_unwrapping
  - function_body_length
  - implicitly_unwrapped_optional
  - line_length
  - type_body_length
  - type_name

opt_in_rules:
  - discouraged_direct_init
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - single_test_class
  - xctfail_message

discouraged_direct_init:
  types:
    - Bundle
    - UIDevice
    - UIWindow