name: Testing
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop
jobs:
  test:
    name: Testing SWDestiny Trades app
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: 12.0
      - name: Install Dependencies (CocoaPods Action)
        run: |
          pod install --repo-update
        shell: bash
      - uses: ty0x2333/cocoapods-action@0.2.0
        with:
          additional_build_params: -destination 'platform=iOS Simulator,name=iPhone X,OS=14.0'
          additional_lint_params: --private
      - name: Testing iOS app
        run: exec ./.github/scripts/test_app.sh
