name: Testing
on: [push, pull_request]

env:
  TUIST_TOKEN: ${{ secrets.TUIST_CLOUD_TOKEN }}
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  test:
    name: Testing SWDestiny Trades app
    runs-on: macos-26
    strategy:
      matrix:
        scheme: [
          SWDestinyTrades
        ]
        workspace: [
          swdestiny-trades.xcworkspace
        ]
        destination: [
          'platform=iOS Simulator,name=iPhone 17 Pro,OS=26.2'
        ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_$(cat .xcode-version).app

      - name: Restore cache
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: Tuist/.build
          key: ${{ runner.os }}-app-${{ hashFiles('Package.resolved') }}

      - name: Install Project Tools
        uses: jdx/mise-action@v3
        with:
          experimental: true

      # - name: Authenticate with Tuist
      #   if: github.event.pull_request.head.repo.fork != true
      #   run: tuist auth login

      # - name: Tuist Cache
      #   if: github.event.pull_request.head.repo.fork != true
      #   run: tuist setup cache

      - name: Install Tuist dependencies
        if: steps.cache-restore.outputs.cache-matched-key == ''
        run: tuist install

      - name: Generate project with tuist
        run: |
          tuist generate --no-open
        shell: bash

      - name: Test ${{ matrix.scheme }} on ${{ matrix.destination }}
        env:
          SWIFT_DISABLE_CAS: 1
        run: |
          xcodebuild -workspace ${{ matrix.workspace }} \
            -scheme ${{ matrix.scheme }} \
            -destination '${{ matrix.destination }}' \
            -resultBundlePath ./coverage/SwdUnitTests.xcresult \
            -enableCodeCoverage YES \
            test | xcpretty && exit ${PIPESTATUS[0]}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          swift_project: SWDestinyTrades
          verbose: true

      - name: Upload Snapshot Failures
        if: failure()
        uses: actions/upload-artifact@v6
        with:
          name: snapshot-failures
          path: SWDestinyTradesTests/FailureDiffs/

      - name: Save cache
        id: cache-save
        uses: actions/cache/save@v4
        with:
          path: Tuist/.build
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}
