name: Testing
on: [push, pull_request]

jobs:
  test:
    name: Testing SWDestiny Trades app
    runs-on: macOS-11
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.4.1
        with:
          xcode-version: 13.2

      - name: Install Mint
        run: |
          brew install mint
        shell: bash      

      - name: Cache CocoaPods libraries
        uses: actions/cache@v3
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Cache Tuist libraries
        uses: actions/cache@v3
        with:
          path: |
            ~/.tuist/Cache
            ~/.tuist/Versions
          key: ${{ runner.os }}-tuist-${{ hashFiles('**/Tuist/Dependencies/Lockfiles/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-tuist-            

      - name: Fetch tuist dependencies
        uses: tuist/tuist-action@0.13.0
        with:
          command: 'fetch'

      - name: Generate project with tuist
        uses: tuist/tuist-action@0.13.0
        with:
          command: 'generate'
          arguments: '--no-open'
      
      - name: Install CocoaPods Dependencies
        run: |
          pod install --repo-update
        shell: bash

      - name: Cache Mint packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.mint/bin
            ~/.mint/packages
          key: ${{ runner.os }}-mint-${{ hashFiles('~/.mint/metadata.json') }}
          restore-keys: |
            ${{ runner.os }}-mint-        

      - name: Install Mint Dependencies
        run: |
          mint bootstrap
        shell: bash        
      
      - name: Testing iOS app
        run: exec ./.github/scripts/test_app.sh
