name: Testing
on: [push, pull_request]

env:
  TUIST_CONFIG_CLOUD_TOKEN: ${{ secrets.TUIST_CONFIG_CLOUD_TOKEN }}

jobs:
  test:
    name: Testing SWDestiny Trades app
    runs-on: macOS-12
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.4.1
        with:
          xcode-version: 13.3

      - name: Install Mint
        run: |
          brew install mint
        shell: bash

      - name: Install Tuist
        run: |
          bash <(curl -Ls https://install.tuist.io)
        shell: bash                  

      - name: Cache CocoaPods libraries
        uses: actions/cache@v3
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Cache Tuist libraries
        uses: actions/cache@v3
        with:
          path: |
            ~/.tuist/Cache
            ~/.tuist/Versions
          key: ${{ runner.os }}-tuist-${{ hashFiles('**/Tuist/Dependencies/Lockfiles/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-tuist-            

      - name: Fetch tuist dependencies
        run: |
          tuist fetch
        shell: bash
          
      - name: Tuist Warm Cache
        env:
          TUIST_CONFIG_CLOUD_TOKEN: ${{ secrets.TUIST_CONFIG_CLOUD_TOKEN }} 
        run: |
          tuist cache warm
        shell: bash          

      - name: Generate project with tuist
        env:
          TUIST_CONFIG_CLOUD_TOKEN: ${{ secrets.TUIST_CONFIG_CLOUD_TOKEN }} 
        run: |          
          tuist generate --no-open
        shell: bash          
      
      - name: Install CocoaPods Dependencies
        run: |
          pod install --repo-update
        shell: bash

      - name: Cache Mint packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.mint/bin
            ~/.mint/packages
          key: ${{ runner.os }}-mint-${{ hashFiles('~/.mint/metadata.json') }}
          restore-keys: |
            ${{ runner.os }}-mint-        

      - name: Install Mint Dependencies
        run: |
          mint bootstrap
        shell: bash        
      
      - name: Testing iOS app
        run: exec ./.github/scripts/test_app.sh
