name: Testing
on: [push, pull_request]

env:
  TUIST_CONFIG_CLOUD_TOKEN: ${{ secrets.TUIST_CONFIG_CLOUD_TOKEN }}

jobs:
  test:
    name: Testing SWDestiny Trades app
    runs-on: macOS-12
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.4.1
        with:
          xcode-version: 14.0.1

      - name: Install Mint
        run: |
          brew install mint
        shell: bash

      - name: Install Tuist
        run: |
          bash <(curl -Ls https://install.tuist.io)
        shell: bash

      - name: Fetch tuist dependencies
        run: |
          tuist fetch
        shell: bash

      - name: Tuist Warm Cache
        run: |
          tuist cache warm
        shell: bash

      - name: Generate project with tuist
        run: |
          tuist generate --no-open
        shell: bash

      - name: Cache Mint packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.mint/bin
            ~/.mint/packages
          key: ${{ runner.os }}-mint-${{ hashFiles('~/.mint/metadata.json') }}
          restore-keys: |
            ${{ runner.os }}-mint-

      - name: Install Mint Dependencies
        run: |
          mint bootstrap
        shell: bash

      - name: Testing iOS app
        run: exec ./.github/scripts/test_app.sh

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2.1.0
